import path from 'node:path';
import { createJiti } from 'jiti';
import { COLLECTOR } from './collector.js';

const j = createJiti(import.meta.url, {
  alias: {
    'simplestyle-js': path.join(import.meta.dirname, 'mock.js'),
  },
  jsx: true,
});

COLLECTOR.length = 0;

/**
 * extracts styles generated by a call to createStyles
 *
 * @param {string} userFilePath
 */
export async function extract(userFilePath) {
  console.info('processing user file:', userFilePath);
  await j.import(userFilePath);

  return COLLECTOR;
}
